### ISSUE TITLE
i can't run npm  this is what happen when i try to run 

### ISSUE THREAD

**Issue by dulanlj** [AdaWaifus/NFT-Generator#1]
<img width="1512" alt="Screenshot 2022-07-08 at 22 01 08" src="https://user-images.githubusercontent.com/104520299/178062554-ee9f510a-a627-4b97-b376-fef3dbb748b1.png">

**Comment by SvenBudak** [comment]
@dulanlj I am very sorry, I forgot to update the `README.md`.
You need to run `npm start-generator`. 
This is because we are currently working on a frontend. (Which is not yet operational)

**Comment by dulanlj** [comment]
ok got it that's fine, I did test this script weeks ago it worked perfectly & I am super looking forward to using this in future projects:)
